services:
  local-db:
    image: 'mysql:5.7'
    container_name: 'infra-container'
    restart: 'always'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '12345678'
      TZ: 'Asia/Seoul'
    volumes:
      - './db/mysql/data:/var/lib/mysql'
      - './db/mysql/init:/docker-entrypoint-initdb.d'
    platform: 'linux/amd64'